### ISSUE TITLE
[BUG]perdayvolume for my bundle is not correct

### ISSUE THREAD

**Issue by YifengMao** [splunk/eventgen#212] opened 2019-05-16 07:16 UTC
**Describe the bug**
perdayvolume/throughput/indexed are not correct.

**To Reproduce**
[longevity_syslog.zip](https://github.com/splunk/eventgen/files/3185808/longevity_syslog.zip)
my bundle is very simple. Here's a table of result
egx cluster 3 node to send data via hec to a standalone splunk host

httpwaitresponse | payloadmaxsize | perdayvolum_total | Throughput | actual
-- | -- | -- | -- | --
false | 256K | 200 | 1477K/s 126G | 130G
true | 256K | 200 | 1474K/s 126G | 130G
true | 256K | 600 | 4054K/s 350G | 355G
true | 256K | 900 | 5863K/s 504G| 498G
true | 256K | 3000(hit bottleneck) | 10907K/s 942G| 1.01T

**Additional context**
version: 6.3.1

**Comment by YifengMao** [comment] 2019-05-16 07:33
2 problems here:

- throughput is less than half of actual throughput.
- actual throughput is greater than perdayvolume, not in a acceptable range (+/- 10%)

**Comment by arctan5x** [comment] 2019-05-28 21:51
Hi Yifeng, would you verify this is the latest version? Also, would you provide environment details such as which cluster, container, etc.

**Comment by li-wu** [comment] 2019-05-31 08:43
Some testing result:
1. Setting `persistentQueueSize` and `queueSize` with 500MB to 1GB does not take effect;
2. Using this pr https://github.com/splunk/eventgen/pull/192 does not work;

Still investigating on it...

**Comment by arctan5x** [comment] 2019-07-30 21:50
@YifengMao would this be still valid? If not, may I close it?

**Comment by li-wu** [comment] 2019-07-31 01:38
@arctan5x I think this is still valid and not solved. This is also related to how we are going to measure the performance of Eventgen.

**Comment by GordonWang** [comment] 2019-09-19 07:53
The issue is resolved. I verified in the test env. 
splunk cluster: 3 indexers and 1 SH.
set the perday volume size as 1000GB.

Then, use 2 spl to check the indexed data size. The result is near 1000GB in either way.  The volume size deviation is less than 1%.

Here are the screenshots.
![image](https://user-images.githubusercontent.com/4759002/65224342-8f728300-daf5-11e9-8df9-80d938257e42.png)


![image](https://user-images.githubusercontent.com/4759002/65224352-94373700-daf5-11e9-82ec-31623e4d1d62.png)

**Closed** 2019-09-19 07:53 UTC
Labels: bug
