### ISSUE TITLE
[BUG] The `timezone` parameter doesn't work when Eventgen is run as a Splunk app

### ISSUE THREAD

**Issue by hexecute** [splunk/eventgen#321] opened 2019-10-18 21:59 UTC
**Describe the bug**
The `timezone` parameter is ignored when using SA-Eventgen.

**To Reproduce**
1. Install and setup SA-Eventgen 6.5.2 (using the eventgen.conf below)
2. Look at the data coming in

**Expected behavior**
The `timezone` parameter should be respected. The event data coming into Splunk should have a different timestamp than on the original events.

**Actual behavior**
The event data coming into Splunk has the same timestamp of the original events.

**Sample files and eventgen.conf file**
[eventgen.conf.txt](https://github.com/splunk/eventgen/files/3745809/eventgen.conf.txt)

**Do you run eventgen with SA-eventgen?**
Yes

**If you are using SA-Eventgen with Splunk (please complete the following information):**
 - Eventgen Version [e.g. 22]
6.5.2
 - Splunk Version[e.g. 7.1.3]
8.0.0
 - What other apps you have installed in Splunk etc/apps?
None

**Comment by GordonWang** [comment] 2019-12-02 11:35
I use the uploaded config file and tried to reproduce this issue. But I cannot reproduce it. 
See the attachment pic 
![image](https://user-images.githubusercontent.com/4759002/69956340-ae03ea00-153a-11ea-8bfc-61e81e345e15.png)

Current China Standard time is about **2019-12-2 19:31**. 
And the timezone config is 
```
timezone = -0100
```
So, the time diff is about 9 hours early. This is the expected behavior.

**Comment by GordonWang** [comment] 2019-12-13 03:22
@hexecute l close this ticket as can not reproduce.
feel free to reopen it if you have more findings.

**Closed by GordonWang** 2019-12-13 03:22 UTC
Labels: bug
