### ISSUE TITLE
eventgen throws exception when processing multiple sample files from command line

### ISSUE THREAD

**Issue by coleman07** [splunk/eventgen#17] opened 2014-06-17 21:51 UTC
I ran eventgen using the following command when loading data from the sample data set provided with the windows tech add on:

python bin/eventgen.py README/eventgen.conf.windows

It throws an exception at line 402 eventgenconfig.py:
Traceback (most recent call last):
  File "bin/eventgen.py", line 143, in <module>
    c.parse()
  File "/opt/splunk/etc/apps/eventgen/lib/eventgenconfig.py", line 402, in parse
    sourcesetting = getattr(overridesample, settingname)
AttributeError: Sample instance has no attribute 'eai:userName'

I fixed it by putting this code after the following lines of code:
  for settingname in self._validSettings:
                        if settingname not in ['eai:acl', 'blacklist', 'disabled', 'name']:

  for settingname in self._validSettings:
         if settingname not in ['eai:acl', 'blacklist', 'disabled', 'name']:
                if not self.splunkEmbedded and settingname in ['eai:username','eai:appname']:
                            continue

I am not much of a programmer so my solution is not as compact as I would like but it works. Hope someone could find a more elegant solution.
I don't have line numbers since I inserted a bunch of logger.debug statements to see how the code works.

**Comment by coccyx** [comment] 2015-08-21 04:30
Not sure I understand this.  Can you reproduce on the current dev branch?

**Comment by arctan5x** [comment] 2018-10-30 23:12
Since this issue has been open for a long time and we did a major overhaul of the project into version 6.x.x, I am closing this issue. Please open a NEW issue if you experience a similar issue with the latest version.

**Closed by arctan5x** 2018-10-30 23:12 UTC
